//
//  ChoreEditViewController.swift
//  ChoresForCoinsiOS
//
//  Created by Andrew Harrington on 6/16/18.
//  Copyright © 2018 Daniel Rivera, Andrew Harrington. All rights reserved.
//

import UIKit
import Firebase
import FirebaseUI
import MobileCoreServices

class ChoreEditViewController: UIViewController, UIImagePickerControllerDelegate, UINavigationControllerDelegate {
    
    @IBOutlet weak var choreImageUIButton: UIButton!
    @IBOutlet weak var choreNameTextField: UITextField!
    @IBOutlet weak var usernameTextField: UITextField!
    @IBOutlet weak var choreDescriptionTextView: UITextView!
    @IBOutlet weak var startDateTextField: UITextField!
    @IBOutlet weak var dueDateTextField: UITextField!
    @IBOutlet weak var choreValueTextField: UITextField!
    @IBOutlet weak var choreNoteTextView: UITextView!
    @IBOutlet weak var usernameLabel: UILabel!
    @IBOutlet weak var coinAmtLabel: UILabel!
    @IBOutlet weak var profileButton: UIButton!
    
     private var imagePicker: UIImagePickerController!
    
    // create date picker
    let picker = UIDatePicker()
    
    var ref: DatabaseReference?
    var userID: String?
    var parentID: String?
    var choreId: String?
    var idFound = false
    var children = [ChildUser] ()
    var coinTotals = [RunningTotal] ()
    var runningTotal = 0
    
    override func viewDidLoad() {
        super.viewDidLoad()
        
        //gets the firebase generated id
        userID = (Auth.auth().currentUser?.uid)!
        
        //define ref variable
        ref = Database.database().reference()
        
        checkDatabase()
        
        // set up date pickers
        createDatePickerStart()
        createDatePickerDue()
        
        //gets the custom parent id created in the registration
        getParentId()
        
        // get photo for profile button
        getPhoto()
        
        //pre populate choe information from exisitng chore.
        displayChoreInfo()
    }
    
    override func viewWillAppear(_ animated: Bool) {
        getRunningTotal()
        getPhoto()
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    func checkDatabase() {
        
        let databaseRef = Database.database().reference().child("user")
        
        if let uid = Auth.auth().currentUser?.uid {
            
            databaseRef.observe(.value) { (snapshot) in
                
                if snapshot.exists(){
                    if let userIdDictionary = snapshot.value as? NSDictionary{
                        for id in userIdDictionary.keyEnumerator(){
                            if let userID = id as? String{
                                if userID == uid {
                                    // user is in database
                                    self.idFound = true
                                    self.displayHeaderName()
                                    return
                                }
                                
                            }
                        }
                    }
                }
            }
            
        }
        
        
        if !idFound {
            
            //user not in the database. Registration segue is called
            let vc = UIStoryboard.init(name: "Main", bundle: Bundle.main).instantiateViewController(withIdentifier: "parentChildVC") as? ParentChildViewController
            self.navigationController?.pushViewController(vc!, animated: true)
            
        }
        
    }
    
    func updateChore(id: String){
        
        //id is the choreID. Takes the information inputted or generated by the form and updates chore.
        
        if isTextViewValid(textView: choreNameTextField) {
            
            let name = choreNameTextField.text!
            ref?.child("chores").child(id).updateChildValues(["chore_name" : name])
        }
        
        if isTextViewValid(textView: usernameTextField){
        
            let userName = usernameTextField.text!
            
        ref?.child("chores").child(id).updateChildValues(["chore_username" : userName])

        }
        
        if isUITextViewValid(textView: choreDescriptionTextView) {
            
            let description = choreDescriptionTextView.text!
            ref?.child("chores").child(id).updateChildValues(["chore_description" : description])
        }
        
        if isTextViewValid(textView: startDateTextField){
            
            let startDate = startDateTextField.text!
            
            ref?.child("chores").child(id).updateChildValues(["start_date" : startDate])
            
        }
        
        if isTextViewValid(textView: dueDateTextField){
            
            let dueDate = dueDateTextField.text!
            
            ref?.child("chores").child(id).updateChildValues(["due_date" : dueDate])
            
        }
        
        if isUITextViewValid(textView: choreNoteTextView){
            
            let choreNote = startDateTextField.text!
            
            ref?.child("chores").child(id).updateChildValues(["chore_note" : choreNote])
            
        }
        
        if isTextViewValid(textView: choreValueTextField){
            
            let choreValue = choreValueTextField.text!
            
            ref?.child("chores").child(id).updateChildValues(["number_coins" : choreValue])
            
        }
        
        
        // TODO: Add alert that says the chore was saved
        AlertController.showAlert(self, title: "Chore Updated", message: "Values have been changed for the current Chore.")
    }
    
    func createDatePickerStart() {
        // create toolbar for done button
        let toolbar = UIToolbar()
        toolbar.sizeToFit()
        
        // done button
        let done = UIBarButtonItem(barButtonSystemItem: .done, target: nil, action: #selector(donePressedStart))
        toolbar.setItems([done], animated: false)
        
        startDateTextField.inputAccessoryView = toolbar
        startDateTextField.inputView = picker
        
        // format picker for date only
        picker.datePickerMode = .date
    }
    
    func createDatePickerDue() {
        // create toolbar for done button
        let toolbar = UIToolbar()
        toolbar.sizeToFit()
        
        // done button
        let done = UIBarButtonItem(barButtonSystemItem: .done, target: nil, action: #selector(donePressedDue))
        toolbar.setItems([done], animated: false)
        
        dueDateTextField.inputAccessoryView = toolbar
        dueDateTextField.inputView = picker
        
        // format picker for date only
        picker.datePickerMode = .date
    }
    
    @objc func donePressedStart() {
        // format date
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        let dateString = formatter.string(from: picker.date)
        
        startDateTextField.text = "\(dateString)"
        self.view.endEditing(true)
    }
    
    @objc func donePressedDue() {
        // format date
        let formatter = DateFormatter()
        formatter.dateStyle = .medium
        let dateString = formatter.string(from: picker.date)
        
        dueDateTextField.text = "\(dateString)"
        self.view.endEditing(true)
    }
    
    func displayHeaderName(){
        let databaseRef = Database.database().reference()
        
        if let uid = Auth.auth().currentUser?.uid {
            
            databaseRef.child("user").child(uid).observeSingleEvent(of: .value) { (snapshot) in
                
                let value = snapshot.value as? NSDictionary
                if let name = value?["user_name"] as? String{
                    self.usernameLabel.text = name
                }
            }
        }
    }
    
    func getRunningTotal(){
        
        getChildren()
        getCoinTotals()
    }
    
    //gets the parent generated id from the user's node in the database
    func getParentId(){
        if let actualUID = userID{
            _ = Database.database().reference().child("user").child(actualUID).observeSingleEvent(of: .value) { (snapshot) in
                let value = snapshot.value as? NSDictionary
                let id = value?["parent_id"] as? String
                if let actualID = id{
                    self.parentID = actualID
                }
            }
        }
        
    }
    
    // gets all children with same parent id as user
    func getChildren() {
        children.removeAll()
        
        _ = Database.database().reference().observeSingleEvent(of: .value) { (snapshot) in
            let dictRoot = snapshot.value as? [String:AnyObject] ?? [:]
            let dictUsers = dictRoot["user"] as? [String:AnyObject] ?? [:]
         
            for key in Array(dictUsers.keys) {
                self.children.append(ChildUser(dictionary: (dictUsers[key] as? [String:AnyObject])!, key: key))
                self.children = self.children.filter({$0.parentid == self.parentID})
                self.children = self.children.filter({$0.userparent! == false})
                
            }
        }
        
    }
    
    func getCoinTotals() {
        coinTotals.removeAll()
        
        _ = Database.database().reference().observeSingleEvent(of: .value) { (snapshot) in
            let dictRoot = snapshot.value as? [String:AnyObject] ?? [:]
            let dictRunningTotal = dictRoot["running_total"] as? [String:AnyObject] ?? [:]
            var count = 0
            for key in Array(dictRunningTotal.keys) {
                self.coinTotals.append(RunningTotal(dictionary: (dictRunningTotal[key] as? [String:AnyObject])!, key: key))
                
                count += 1
            }
            
            var sumTotal = 0
            
            for coinTotal in self.coinTotals {
                for child in self.children {
                    if coinTotal.userid == child.userid {
                        if let total = coinTotal.cointotal {
                            sumTotal += total
                        }
                    }
                }
            }
            
            self.coinAmtLabel.text = String(sumTotal)
        }
    }
    
    func getPhoto() {
        
        let DatabaseRef = Database.database().reference()
        if let uid = userID{
            DatabaseRef.child("user").child(uid).observeSingleEvent(of: .value) { (snapshot) in
                
                let value = snapshot.value as? NSDictionary
                //gets the image URL from the user database
                if let profileURL = value?["profile_image_url"] as? String{
                    
                    self.profileButton.loadImagesUsingCacheWithUrlString(urlString: profileURL, inViewController: self)
                    //turn button into a circle
                    self.profileButton.layer.cornerRadius = self.profileButton.frame.width/2
                    self.profileButton.layer.masksToBounds = true
                }
            }
            
        }
    }
    
    func displayChoreInfo(){
        
        
        if let cid = choreId{
            ref?.child("chores").child(cid).observeSingleEvent(of: .value, with: { (snapshot) in
                
                if snapshot.exists(){
                    
                    let value = snapshot.value as? NSDictionary
                    
                    if let choreName = value?["chore_name"] as? String {
                        self.choreNameTextField.text = choreName
                    }
                    
                    if let choreDescription = value?["chore_description"] as? String  {
                        self.choreDescriptionTextView.text = choreDescription
                    }
                    
                    if let choreUserName = value?["chore_username"] as? String {
                        self.usernameTextField.text = choreUserName
                    }
                    
                    if let choreStartDate = value?["start_date"] as? String {
                        self.startDateTextField.text = choreStartDate
                    }
                    
                    if let choreDueDate = value?["due_date"] as? String {
                        self.dueDateTextField.text = choreDueDate
                    }
                    
                    if let choreValue = value?["chore_value"] as? String {
                        self.choreValueTextField.text = choreValue
                    }
                    
                    if let choreNote = value?["chore_note"] as? String {
                        self.choreNoteTextView.text = choreNote
                    }
                    
                    if let imageUrl = value?["image_url"] as? String {
                        self.choreImageUIButton.loadImagesUsingCacheWithUrlString(urlString: imageUrl, inViewController: self)
                    }
                }
            })
        }
    }
    
    func isTextViewValid(textView: UITextField) -> Bool{
        
        if (textView.text?.isEmpty)! {
            
            AlertController.showAlert(self, title: "Missing Information", message: "Please ensure all text fileds are completed.")
            
            return false
        }  else {
            
            return true
        }
    }
    
    func isUITextViewValid(textView: UITextView) -> Bool{
        
        if (textView.text?.isEmpty)! {
            
            AlertController.showAlert(self, title: "Missing Information", message: "Please ensure all text fileds are completed.")
            
            return false
        }  else {
            
            
            return true
        }
    }
    
    func removeChildNode(child: String){
        if let dbRef = ref?.child("chores").child(child){
            
            dbRef.removeValue()
        }
        
        let storRef = Storage.storage().reference()
            
            storRef.child(child).delete { (error) in
                if let error = error {
                    AlertController.showAlert(self, title: "Delete Image from Storage Error", message: error.localizedDescription)
                } else {
                    AlertController.showAlert(self, title: "Delete Success", message: "Chore and chore image deleted.")
                }
        }
    }
    
    @IBAction func doGoBack(_ sender: UIButton) {
        dismiss(animated: true, completion: nil)
    }
    
    @IBAction func changeChorePicture(_ sender: UIButton) {
    
        //instantiates the imagePicker
        imagePicker = UIImagePickerController()
        imagePicker.delegate = self
        
        //if the camera is not available, use the photo library
        if UIImagePickerController.isSourceTypeAvailable(.camera){
            imagePicker.sourceType = .camera
        } else {
            
            //may remove this option if current image from camera is necessary.
            imagePicker.sourceType = .photoLibrary
        }
        
        //image can be edited and sets the mediatype to the source type which is the camera
        imagePicker.allowsEditing = true
        imagePicker.mediaTypes = UIImagePickerController.availableMediaTypes(for: imagePicker.sourceType)!
        
        self.present(imagePicker, animated: true, completion: nil)
    }
    
    //function to access storage
    
    func storeImage(image: UIImage){
        
        let imageName = "\(choreId!)"
        let storageRef = Storage.storage().reference().child("\(imageName).png")
        
        
        if let uploadData = UIImagePNGRepresentation(image) {
            
            storageRef.putData(uploadData, metadata: nil) { (metadata, error) in
                if error != nil {
                    AlertController.showAlert(self, title: "Image Upload Error", message: (error?.localizedDescription)! )
                    return
                }
                
                storageRef.downloadURL(completion: { (url, error) in
                    if let error = error {
                        AlertController.showAlert(self, title: "Download URL Error", message: error.localizedDescription)
                        return
                    } else {
                        if let urlString = url?.absoluteString{
                            self.createChoreImageURL(imageUrl: urlString)
                        }
                    }
                })
                
            }
            
        }
        
    }
    
    private func createChoreImageURL(imageUrl: String){
        
        let ref = Database.database().reference()
        
        ref.child("chores/\(choreId!)/image_url").setValue(imageUrl)
    }
    
    func imagePickerController(_ picker: UIImagePickerController, didFinishPickingMediaWithInfo info: [String : Any]) {
        
        let mediaType = info[UIImagePickerControllerMediaType] as! String
        
        if mediaType == (kUTTypeImage as String){
            
            // a photo was taken
            let ref = Database.database().reference().child("chores")
            
            // updates the chore completed from false to true
            ref.child("\(choreId!)").updateChildValues(["chore_completed" : true])
            
            var selectedImageFromPicker: UIImage?
            
            if let editedImage = info["UIImagePickerControllerEditedImage"]{
                // save edited image
                selectedImageFromPicker = editedImage as? UIImage
                
            } else if let originalImage = info["UIImagePickerControllerOriginalImage"]{
                // save original image
                selectedImageFromPicker = originalImage as? UIImage
            }
            
            //selectedImage unwrapped to be saved.
            if let selectedImage = selectedImageFromPicker {
                storeImage(image: selectedImage)
                
            }
            dismiss(animated: true, completion: nil)
            
            
            
        } else {
            // a video was taken and do nothing.
        }
    }
    
    func imagePickerControllerDidCancel(_ picker: UIImagePickerController) {
        
        dismiss(animated: true, completion: nil)
    }
    
    @IBAction func deleteChore(_ sender: UIButton) {
        
        if let id = choreId {
            removeChildNode(child: id)
            performSegue(withIdentifier: "segueToList", sender: self)
        }
        
    }
    
    //calls the updatechore function to rewrite the chore object
    @IBAction func saveChore(_ sender: UIButton) {
        if let cid = choreId {
            updateChore(id: cid)
            
            
            performSegue(withIdentifier: "segueToList", sender: self)
        }
    }
    
}
